// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VirtLib.Windows.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VirtualMachineFeature : object, Xunit.IClassFixture<VirtualMachineFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "VirtualMachine.feature"
#line hidden
        
        public VirtualMachineFeature(VirtualMachineFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "VirtualMachine", "\tValidate VM logic and functionality", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get virtual machine from home machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Get virtual machine from home machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public async System.Threading.Tasks.Task GetVirtualMachineFromHomeMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Get virtual machine from home machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
        await testRunner.GivenAsync("hyper-v host running on localhost", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
     await testRunner.WhenAsync("I get vm with name \"devbox1\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
     await testRunner.ThenAsync("vm should exist with name \"devbox1\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get virtual machine from work machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Get virtual machine from work machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public async System.Threading.Tasks.Task GetVirtualMachineFromWorkMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Get virtual machine from work machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
        await testRunner.GivenAsync("hyper-v host running on localhost", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
        await testRunner.WhenAsync("I get vm with name \"ubuntu\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
        await testRunner.ThenAsync("vm should exist with name \"ubuntu\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create gen-1 virtual machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Create gen-1 virtual machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public async System.Threading.Tasks.Task CreateGen_1VirtualMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Create gen-1 virtual machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
        await testRunner.GivenAsync("hyper-v host running on localhost", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
        await testRunner.AndAsync("ubuntu image \"ubuntu2204.iso\" is downloaded from url \"https://releases.ubuntu.com" +
                        "/jammy/ubuntu-22.04.4-live-server-amd64.iso\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
                Reqnroll.Table table3 = new Reqnroll.Table(new string[] {
                            "Name",
                            "Value"});
                table3.AddRow(new string[] {
                            "Username",
                            "ubuntu"});
                table3.AddRow(new string[] {
                            "Password",
                            "ubuntu"});
                table3.AddRow(new string[] {
                            "SshPublicKeyFile",
                            "ubuntu_rsa.pub"});
                table3.AddRow(new string[] {
                            "CpuCount",
                            "2"});
                table3.AddRow(new string[] {
                            "MemoryInMB",
                            "2048"});
                table3.AddRow(new string[] {
                            "HardDiskSizeInGB",
                            "20"});
                table3.AddRow(new string[] {
                            "SwitchName",
                            "Default Switch"});
#line 20
        await testRunner.WhenAsync("I create gen 1 vm with name \"ubuntu2\"", ((string)(null)), table3, "When ");
#line hidden
#line 29
        await testRunner.ThenAsync("vm should exist with name \"ubuntu2\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
        await testRunner.AndAsync("delete vm with name \"ubuntu2\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create gen-2 virtual machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Create gen-2 virtual machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public async System.Threading.Tasks.Task CreateGen_2VirtualMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Create gen-2 virtual machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
        await testRunner.GivenAsync("hyper-v host running on localhost", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
        await testRunner.AndAsync("ubuntu image \"ubuntu2204.iso\" is downloaded from url \"https://releases.ubuntu.com" +
                        "/jammy/ubuntu-22.04.4-live-server-amd64.iso\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
                Reqnroll.Table table4 = new Reqnroll.Table(new string[] {
                            "Name",
                            "Value"});
                table4.AddRow(new string[] {
                            "Username",
                            "ubuntu"});
                table4.AddRow(new string[] {
                            "Password",
                            "ubuntu"});
                table4.AddRow(new string[] {
                            "SshPublicKeyFile",
                            "ubuntu_rsa.pub"});
                table4.AddRow(new string[] {
                            "CpuCount",
                            "2"});
                table4.AddRow(new string[] {
                            "MemoryInMB",
                            "2048"});
                table4.AddRow(new string[] {
                            "HardDiskSizeInGB",
                            "20"});
                table4.AddRow(new string[] {
                            "SwitchName",
                            "Default Switch"});
#line 36
        await testRunner.WhenAsync("I create gen 2 vm with name \"ubuntu3\"", ((string)(null)), table4, "When ");
#line hidden
#line 45
        await testRunner.ThenAsync("vm should exist with name \"ubuntu3\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
        await testRunner.AndAsync("delete vm with name \"ubuntu3\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await VirtualMachineFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await VirtualMachineFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
