<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RootNamespace>VirtLib.Windows.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CRP.Common.Config" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtLib.Windows\VirtLib.Windows.csproj" />
  </ItemGroup>
</Project>
