// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 12/5/2025 using wmigen
//      Source root.HyperVCluster.v2
//////////////////////////////////////////////
use crate::wmi;
use crate::cim;


/// Msvm_CollectionManagementService struct
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Msvm_CollectionManagementService {
    #[serde(flatten)]
    pub base: CIM_Service,
}

impl Msvm_CollectionManagementService {
    /// Creates a new instance of the struct
    pub fn new() -> Self {
        Self {
            base: CIM_Service::new(),
        }
    }


/// 

    /// * `id` - String containing a GUID used to identify the group. The GUID must be unique, or the call will fail. If no string is specified, a new unique Id will be generated by the service. (String)
    /// * `name` - String containing a user defined name for the new collection. If no string is specified, the default new collection name will be used. (String)
    /// * `type` - An enumeration value that specifies what type of collection object to create. (u16)

    /// * `defined_collection` - If successful, outputs a string containing a reference to the created collection. (CIM_CollectionOfMSEs)
    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn define_collection(&self, name: &String, id: &String, type: u16, defined_collection: &mut CIM_CollectionOfMSEs, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Name".to_string(), value: name.into() });
        args.push(MethodParameter { name: "Id".to_string(), value: id.into() });
        args.push(MethodParameter { name: "Type".to_string(), value: type.into() });

        let result = self.invoke_method_with_job("DefineCollection", &args)?;
        let defined_collection = result.get_value("DefinedCollection")?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }


/// 

    /// * `collection` - A reference to the collection that will be deleted. (CIM_CollectionOfMSEs)

    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn destroy_collection(&self, collection: CIM_CollectionOfMSEs, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Collection".to_string(), value: collection.into() });

        let result = self.invoke_method_with_job("DestroyCollection", &args)?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }


/// 

    /// * `collection` - A reference to the collection that will be renamed. (CIM_CollectionOfMSEs)
    /// * `new_name` - A string containing the new name for the collection. (String)

    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn rename_collection(&self, collection: CIM_CollectionOfMSEs, new_name: &String, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Collection".to_string(), value: collection.into() });
        args.push(MethodParameter { name: "NewName".to_string(), value: new_name.into() });

        let result = self.invoke_method_with_job("RenameCollection", &args)?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }


/// 

    /// * `collection` - A reference to the collection the member should be added to. (CIM_CollectionOfMSEs)
    /// * `member` - A reference to the the member that should be added to the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection. (CIM_ManagedElement)

    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn add_member(&self, member: CIM_ManagedElement, collection: CIM_CollectionOfMSEs, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Member".to_string(), value: member.into() });
        args.push(MethodParameter { name: "Collection".to_string(), value: collection.into() });

        let result = self.invoke_method_with_job("AddMember", &args)?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }


/// 

    /// * `collection` - A reference to the collection the member should be removed from. (CIM_CollectionOfMSEs)
    /// * `member` - A reference to the the member that should be removed from the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection. (CIM_ManagedElement)

    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn remove_member(&self, member: CIM_ManagedElement, collection: CIM_CollectionOfMSEs, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Member".to_string(), value: member.into() });
        args.push(MethodParameter { name: "Collection".to_string(), value: collection.into() });

        let result = self.invoke_method_with_job("RemoveMember", &args)?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }


/// 

    /// * `collection_id` - A string containing the GUID instance ID for the collection from which the member should be removed. (String)
    /// * `member` - A reference to the the member that should be removed from the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection. (CIM_ManagedElement)

    /// * `job` -  (CIM_ConcreteJob)
    /// * `return_value` -  (u32)
    pub fn remove_member_by_id(&self, member: CIM_ManagedElement, collection_id: &String, job: &mut CIM_ConcreteJob, action: UserAction, percent_complete: uint, timeout: int) -> Result<(), WmiError> {
        let mut args = Vec::new();
        args.push(MethodParameter { name: "Member".to_string(), value: member.into() });
        args.push(MethodParameter { name: "CollectionId".to_string(), value: collection_id.into() });

        let result = self.invoke_method_with_job("RemoveMemberById", &args)?;
        let job = result.get_value("Job")?;
        Ok(result.return_value)

    }

}

impl Msvm_CollectionManagementService {
    /// Gets the related Msvm_ComputerSystem object(s)
    pub fn get_related__computer_system(&self) -> Result<Msvm_ComputerSystem, WmiError> {
        self.get_related("Msvm_ComputerSystem")
    }

}

