// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Common.Config.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LoggingFeature : object, Xunit.IClassFixture<LoggingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "logging.feature"
#line hidden
        
        public LoggingFeature(LoggingFeature.FixtureData fixtureData, Common_Config_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "logging", "\tSimple calculator for adding two numbers", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="console logger")]
        [Xunit.TraitAttribute("FeatureTitle", "logging")]
        [Xunit.TraitAttribute("Description", "console logger")]
        [Xunit.TraitAttribute("Category", "unit_test")]
        [Xunit.TraitAttribute("Category", "logging")]
        [Xunit.TraitAttribute("Category", "prod")]
        public void ConsoleLogger()
        {
            string[] tagsOfScenario = new string[] {
                    "unit_test",
                    "logging",
                    "prod"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("console logger", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
     testRunner.Given("logger is configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level",
                            "Message"});
                table6.AddRow(new string[] {
                            "Debug",
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in" +
                                "cididunt ut labore et dolore magna aliqua."});
                table6.AddRow(new string[] {
                            "Information",
                            "Pharetra pharetra massa massa ultricies mi quis hendrerit."});
                table6.AddRow(new string[] {
                            "Warning",
                            "Fusce ut placerat orci nulla. Ac ut consequat semper viverra nam."});
                table6.AddRow(new string[] {
                            "Error",
                            "Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna."});
#line 7
        testRunner.When("I create several logs", ((string)(null)), table6, "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level",
                            "Message"});
                table7.AddRow(new string[] {
                            "Debug",
                            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in" +
                                "cididunt ut labore et dolore magna aliqua."});
                table7.AddRow(new string[] {
                            "Information",
                            "Pharetra pharetra massa massa ultricies mi quis hendrerit."});
                table7.AddRow(new string[] {
                            "Warning",
                            "Fusce ut placerat orci nulla. Ac ut consequat semper viverra nam."});
                table7.AddRow(new string[] {
                            "Error",
                            "Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna."});
#line 13
        testRunner.Then("the following messages should be logged", ((string)(null)), table7, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                LoggingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                LoggingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
