// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 12/5/2025 using wmigen
//      Source Eventlog_Type
//////////////////////////////////////////////

/// Eventlog_Type enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[repr(i32)]
pub enum Eventlog_Type {
    /// ISCSI_ERR_TDI_CONNECT_FAILED
    #[serde(rename = "ISCSI_ERR_TDI_CONNECT_FAILED")]
    ISCSIERRTDICONNECTFAILED = 1,
    /// ISCSI_ERR_INSUFFICIENT_SESSION_RESOURCES
    #[serde(rename = "ISCSI_ERR_INSUFFICIENT_SESSION_RESOURCES")]
    ISCSIERRINSUFFICIENTSESSIONRESOURCES = 2,
    /// ISCSI_ERR_INVALID_COMMAND_SEQUENCE_NUMBER
    #[serde(rename = "ISCSI_ERR_INVALID_COMMAND_SEQUENCE_NUMBER")]
    ISCSIERRINVALIDCOMMANDSEQUENCENUMBER = 3,
    /// ISCSI_ERR_INVALID_BURST_LENGTH
    #[serde(rename = "ISCSI_ERR_INVALID_BURST_LENGTH")]
    ISCSIERRINVALIDBURSTLENGTH = 4,
    /// ISCSI_ERR_SETUP_NETWORK_NODE
    #[serde(rename = "ISCSI_ERR_SETUP_NETWORK_NODE")]
    ISCSIERRSETUPNETWORKNODE = 5,
    /// ISCSI_ERR_INSUFFICIENT_CONNECTION_RESOURCES
    #[serde(rename = "ISCSI_ERR_INSUFFICIENT_CONNECTION_RESOURCES")]
    ISCSIERRINSUFFICIENTCONNECTIONRESOURCES = 6,
    /// ISCSI_ERR_SEND_FAILED
    #[serde(rename = "ISCSI_ERR_SEND_FAILED")]
    ISCSIERRSENDFAILED = 7,
    /// ISCSI_ERR_ISCSI_REQUEST_TIMEOUT
    #[serde(rename = "ISCSI_ERR_ISCSI_REQUEST_TIMEOUT")]
    ISCSIERRISCSIREQUESTTIMEOUT = 8,
    /// ISCSI_ERR_SCSI_REQUEST_TIMEOUT
    #[serde(rename = "ISCSI_ERR_SCSI_REQUEST_TIMEOUT")]
    ISCSIERRSCSIREQUESTTIMEOUT = 9,
    /// ISCSI_ERR_LOGIN_FAILED
    #[serde(rename = "ISCSI_ERR_LOGIN_FAILED")]
    ISCSIERRLOGINFAILED = 10,
    /// ISCSI_ERR_LOGIN_PDU_ERROR
    #[serde(rename = "ISCSI_ERR_LOGIN_PDU_ERROR")]
    ISCSIERRLOGINPDUERROR = 11,
    /// ISCSI_ERR_INVALID_LOGIN_REDIRECT_DATA
    #[serde(rename = "ISCSI_ERR_INVALID_LOGIN_REDIRECT_DATA")]
    ISCSIERRINVALIDLOGINREDIRECTDATA = 12,
    /// ISCSI_ERR_INVALID_AUTHMETHOD
    #[serde(rename = "ISCSI_ERR_INVALID_AUTHMETHOD")]
    ISCSIERRINVALIDAUTHMETHOD = 13,
    /// ISCSI_ERR_INVALID_CHAP_ALGORITHM
    #[serde(rename = "ISCSI_ERR_INVALID_CHAP_ALGORITHM")]
    ISCSIERRINVALIDCHAPALGORITHM = 14,
    /// ISCSI_ERR_INVALID_CHAP_CHALLENGE
    #[serde(rename = "ISCSI_ERR_INVALID_CHAP_CHALLENGE")]
    ISCSIERRINVALIDCHAPCHALLENGE = 15,
    /// ISCSI_ERR_INVALID_KEY_DURING_CHAP
    #[serde(rename = "ISCSI_ERR_INVALID_KEY_DURING_CHAP")]
    ISCSIERRINVALIDKEYDURINGCHAP = 16,
    /// ISCSI_ERR_INVALID_CHAP_RESPONSE
    #[serde(rename = "ISCSI_ERR_INVALID_CHAP_RESPONSE")]
    ISCSIERRINVALIDCHAPRESPONSE = 17,
    /// ISCSI_ERR_HEADER_DIGEST_NEEDED
    #[serde(rename = "ISCSI_ERR_HEADER_DIGEST_NEEDED")]
    ISCSIERRHEADERDIGESTNEEDED = 18,
    /// ISCSI_ERR_HEADER_DATA_NEEDED
    #[serde(rename = "ISCSI_ERR_HEADER_DATA_NEEDED")]
    ISCSIERRHEADERDATANEEDED = 19,
    /// ISCSI_ERR_CONNECTION_LOST
    #[serde(rename = "ISCSI_ERR_CONNECTION_LOST")]
    ISCSIERRCONNECTIONLOST = 20,
    /// ISCSI_ERR_INVALID_DATA_SEGMENT_LENGTH
    #[serde(rename = "ISCSI_ERR_INVALID_DATA_SEGMENT_LENGTH")]
    ISCSIERRINVALIDDATASEGMENTLENGTH = 21,
    /// ISCSI_ERR_HEADER_DIGEST_ERROR
    #[serde(rename = "ISCSI_ERR_HEADER_DIGEST_ERROR")]
    ISCSIERRHEADERDIGESTERROR = 22,
    /// ISCSI_ERR_ISCSI_PDU_ERROR
    #[serde(rename = "ISCSI_ERR_ISCSI_PDU_ERROR")]
    ISCSIERRISCSIPDUERROR = 23,
    /// ISCSI_ERR_UNKNOWN_ISCSI_OPCODE
    #[serde(rename = "ISCSI_ERR_UNKNOWN_ISCSI_OPCODE")]
    ISCSIERRUNKNOWNISCSIOPCODE = 24,
    /// ISCSI_ERR_DATA_DIGEST_ERROR
    #[serde(rename = "ISCSI_ERR_DATA_DIGEST_ERROR")]
    ISCSIERRDATADIGESTERROR = 25,
    /// ISCSI_ERR_EXCESS_DATA_SENT
    #[serde(rename = "ISCSI_ERR_EXCESS_DATA_SENT")]
    ISCSIERREXCESSDATASENT = 26,
    /// ISCSI_ERR_UNEXPECTED_PDU
    #[serde(rename = "ISCSI_ERR_UNEXPECTED_PDU")]
    ISCSIERRUNEXPECTEDPDU = 27,
    /// ISCSI_ERR_INVALID_RTT_PDU
    #[serde(rename = "ISCSI_ERR_INVALID_RTT_PDU")]
    ISCSIERRINVALIDRTTPDU = 28,
    /// ISCSI_ERR_ISCSI_PDU_REJECTED
    #[serde(rename = "ISCSI_ERR_ISCSI_PDU_REJECTED")]
    ISCSIERRISCSIPDUREJECTED = 29,
    /// ISCSI_ERR_INSUFFICIENT_WORKITEM_RESOURCES
    #[serde(rename = "ISCSI_ERR_INSUFFICIENT_WORKITEM_RESOURCES")]
    ISCSIERRINSUFFICIENTWORKITEMRESOURCES = 30,
    /// ISCSI_ERR_INSUFFICIENT_REQ_PACKET_RESOURCES
    #[serde(rename = "ISCSI_ERR_INSUFFICIENT_REQ_PACKET_RESOURCES")]
    ISCSIERRINSUFFICIENTREQPACKETRESOURCES = 31,
    /// ISCSI_WRN_RECEIVED_ASYNC_LOGOUT
    #[serde(rename = "ISCSI_WRN_RECEIVED_ASYNC_LOGOUT")]
    ISCSIWRNRECEIVEDASYNCLOGOUT = 32,
    /// ISCSI_ERR_INVALID_CHAP_CHALLENGE_SIZE
    #[serde(rename = "ISCSI_ERR_INVALID_CHAP_CHALLENGE_SIZE")]
    ISCSIERRINVALIDCHAPCHALLENGESIZE = 33,
    /// ISCSI_INFO_RECONNECTED_TO_TARGET
    #[serde(rename = "ISCSI_INFO_RECONNECTED_TO_TARGET")]
    ISCSIINFORECONNECTEDTOTARGET = 34,
    /// ISCSI_ERR_INVALID_TARGET_CHAP_SECRET
    #[serde(rename = "ISCSI_ERR_INVALID_TARGET_CHAP_SECRET")]
    ISCSIERRINVALIDTARGETCHAPSECRET = 35,
    /// ISCSI_ERR_INVALID_INITIATOR_CHAP_SECRET
    #[serde(rename = "ISCSI_ERR_INVALID_INITIATOR_CHAP_SECRET")]
    ISCSIERRINVALIDINITIATORCHAPSECRET = 36,
    /// ISCSI_ERR_FIPS_NOT_AVAILABLE
    #[serde(rename = "ISCSI_ERR_FIPS_NOT_AVAILABLE")]
    ISCSIERRFIPSNOTAVAILABLE = 37,
    /// ISCSI_ERR_CHAP_NOT_OFFERED
    #[serde(rename = "ISCSI_ERR_CHAP_NOT_OFFERED")]
    ISCSIERRCHAPNOTOFFERED = 38,
    /// ISCSI_ERR_DEVICE_RESET
    #[serde(rename = "ISCSI_ERR_DEVICE_RESET")]
    ISCSIERRDEVICERESET = 39,
    /// ISCSI_ERR_CHAP_OFFERED
    #[serde(rename = "ISCSI_ERR_CHAP_OFFERED")]
    ISCSIERRCHAPOFFERED = 40,
    /// ISCSI_ERR_AUTH_METHOD_NOT_OFFERED
    #[serde(rename = "ISCSI_ERR_AUTH_METHOD_NOT_OFFERED")]
    ISCSIERRAUTHMETHODNOTOFFERED = 41,
    /// ISCSI_ERR_INVALID_STATUS_SEQ_NUM
    #[serde(rename = "ISCSI_ERR_INVALID_STATUS_SEQ_NUM")]
    ISCSIERRINVALIDSTATUSSEQNUM = 42,
}

impl Default for Eventlog_Type {
    fn default() -> Self {
        Self::ISCSIERRTDICONNECTFAILED
    }
}

