// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 12/5/2025 using wmigen
//      Source MemoryError_Type
//////////////////////////////////////////////

/// MemoryError_Type enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[repr(i32)]
pub enum MemoryError_Type {
    /// MCA_WARNING_CACHE
    #[serde(rename = "MCA_WARNING_CACHE")]
    MCAWARNINGCACHE = 1,
    /// MCA_ERROR_CACHE
    #[serde(rename = "MCA_ERROR_CACHE")]
    MCAERRORCACHE = 2,
    /// MCA_WARNING_TLB
    #[serde(rename = "MCA_WARNING_TLB")]
    MCAWARNINGTLB = 3,
    /// MCA_ERROR_TLB
    #[serde(rename = "MCA_ERROR_TLB")]
    MCAERRORTLB = 4,
    /// MCA_WARNING_CPU_BUS
    #[serde(rename = "MCA_WARNING_CPU_BUS")]
    MCAWARNINGCPUBUS = 5,
    /// MCA_ERROR_CPU_BUS
    #[serde(rename = "MCA_ERROR_CPU_BUS")]
    MCAERRORCPUBUS = 6,
    /// MCA_WARNING_REGISTER_FILE
    #[serde(rename = "MCA_WARNING_REGISTER_FILE")]
    MCAWARNINGREGISTERFILE = 7,
    /// MCA_ERROR_REGISTER_FILE
    #[serde(rename = "MCA_ERROR_REGISTER_FILE")]
    MCAERRORREGISTERFILE = 8,
    /// MCA_WARNING_MAS
    #[serde(rename = "MCA_WARNING_MAS")]
    MCAWARNINGMAS = 9,
    /// MCA_ERROR_MAS
    #[serde(rename = "MCA_ERROR_MAS")]
    MCAERRORMAS = 10,
    /// MCA_WARNING_MEM_UNKNOWN
    #[serde(rename = "MCA_WARNING_MEM_UNKNOWN")]
    MCAWARNINGMEMUNKNOWN = 11,
    /// MCA_ERROR_MEM_UNKNOWN
    #[serde(rename = "MCA_ERROR_MEM_UNKNOWN")]
    MCAERRORMEMUNKNOWN = 12,
    /// MCA_WARNING_MEM_1_2
    #[serde(rename = "MCA_WARNING_MEM_1_2")]
    MCAWARNINGMEM12 = 13,
    /// MCA_ERROR_MEM_1_2
    #[serde(rename = "MCA_ERROR_MEM_1_2")]
    MCAERRORMEM12 = 14,
    /// MCA_WARNING_MEM_1_2_5
    #[serde(rename = "MCA_WARNING_MEM_1_2_5")]
    MCAWARNINGMEM125 = 15,
    /// MCA_ERROR_MEM_1_2_5
    #[serde(rename = "MCA_ERROR_MEM_1_2_5")]
    MCAERRORMEM125 = 16,
    /// MCA_WARNING_MEM_1_2_5_4
    #[serde(rename = "MCA_WARNING_MEM_1_2_5_4")]
    MCAWARNINGMEM1254 = 17,
    /// MCA_ERROR_MEM_1_2_5_4
    #[serde(rename = "MCA_ERROR_MEM_1_2_5_4")]
    MCAERRORMEM1254 = 18,
    /// MCA_WARNING_SYSTEM_EVENT
    #[serde(rename = "MCA_WARNING_SYSTEM_EVENT")]
    MCAWARNINGSYSTEMEVENT = 19,
    /// MCA_ERROR_SYSTEM_EVENT
    #[serde(rename = "MCA_ERROR_SYSTEM_EVENT")]
    MCAERRORSYSTEMEVENT = 20,
    /// MCA_WARNING_PCI_BUS_PARITY
    #[serde(rename = "MCA_WARNING_PCI_BUS_PARITY")]
    MCAWARNINGPCIBUSPARITY = 21,
    /// MCA_ERROR_PCI_BUS_PARITY
    #[serde(rename = "MCA_ERROR_PCI_BUS_PARITY")]
    MCAERRORPCIBUSPARITY = 22,
    /// MCA_WARNING_PCI_BUS_PARITY_NO_INFO
    #[serde(rename = "MCA_WARNING_PCI_BUS_PARITY_NO_INFO")]
    MCAWARNINGPCIBUSPARITYNOINFO = 23,
    /// MCA_ERROR_PCI_BUS_PARITY_NO_INFO
    #[serde(rename = "MCA_ERROR_PCI_BUS_PARITY_NO_INFO")]
    MCAERRORPCIBUSPARITYNOINFO = 24,
    /// MCA_WARNING_PCI_BUS_SERR
    #[serde(rename = "MCA_WARNING_PCI_BUS_SERR")]
    MCAWARNINGPCIBUSSERR = 25,
    /// MCA_ERROR_PCI_BUS_SERR
    #[serde(rename = "MCA_ERROR_PCI_BUS_SERR")]
    MCAERRORPCIBUSSERR = 26,
    /// MCA_WARNING_PCI_BUS_SERR_NO_INFO
    #[serde(rename = "MCA_WARNING_PCI_BUS_SERR_NO_INFO")]
    MCAWARNINGPCIBUSSERRNOINFO = 27,
    /// MCA_ERROR_PCI_BUS_SERR_NO_INFO
    #[serde(rename = "MCA_ERROR_PCI_BUS_SERR_NO_INFO")]
    MCAERRORPCIBUSSERRNOINFO = 28,
    /// MCA_WARNING_PCI_BUS_MASTER_ABORT
    #[serde(rename = "MCA_WARNING_PCI_BUS_MASTER_ABORT")]
    MCAWARNINGPCIBUSMASTERABORT = 29,
    /// MCA_ERROR_PCI_BUS_MASTER_ABORT
    #[serde(rename = "MCA_ERROR_PCI_BUS_MASTER_ABORT")]
    MCAERRORPCIBUSMASTERABORT = 30,
    /// MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO
    #[serde(rename = "MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO")]
    MCAWARNINGPCIBUSMASTERABORTNOINFO = 31,
    /// MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO
    #[serde(rename = "MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO")]
    MCAERRORPCIBUSMASTERABORTNOINFO = 32,
    /// MCA_WARNING_PCI_BUS_TIMEOUT
    #[serde(rename = "MCA_WARNING_PCI_BUS_TIMEOUT")]
    MCAWARNINGPCIBUSTIMEOUT = 33,
    /// MCA_ERROR_PCI_BUS_TIMEOUT
    #[serde(rename = "MCA_ERROR_PCI_BUS_TIMEOUT")]
    MCAERRORPCIBUSTIMEOUT = 34,
    /// MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO
    #[serde(rename = "MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO")]
    MCAWARNINGPCIBUSTIMEOUTNOINFO = 35,
    /// MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO
    #[serde(rename = "MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO")]
    MCAERRORPCIBUSTIMEOUTNOINFO = 36,
    /// MCA_WARNING_PCI_BUS_UNKNOWN
    #[serde(rename = "MCA_WARNING_PCI_BUS_UNKNOWN")]
    MCAWARNINGPCIBUSUNKNOWN = 37,
    /// MCA_ERROR_PCI_BUS_UNKNOWN
    #[serde(rename = "MCA_ERROR_PCI_BUS_UNKNOWN")]
    MCAERRORPCIBUSUNKNOWN = 38,
    /// MCA_WARNING_PCI_DEVICE
    #[serde(rename = "MCA_WARNING_PCI_DEVICE")]
    MCAWARNINGPCIDEVICE = 39,
    /// MCA_ERROR_PCI_DEVICE
    #[serde(rename = "MCA_ERROR_PCI_DEVICE")]
    MCAERRORPCIDEVICE = 40,
    /// MCA_WARNING_SMBIOS
    #[serde(rename = "MCA_WARNING_SMBIOS")]
    MCAWARNINGSMBIOS = 41,
    /// MCA_ERROR_SMBIOS
    #[serde(rename = "MCA_ERROR_SMBIOS")]
    MCAERRORSMBIOS = 42,
    /// MCA_WARNING_PLATFORM_SPECIFIC
    #[serde(rename = "MCA_WARNING_PLATFORM_SPECIFIC")]
    MCAWARNINGPLATFORMSPECIFIC = 43,
    /// MCA_ERROR_PLATFORM_SPECIFIC
    #[serde(rename = "MCA_ERROR_PLATFORM_SPECIFIC")]
    MCAERRORPLATFORMSPECIFIC = 44,
    /// MCA_WARNING_UNKNOWN
    #[serde(rename = "MCA_WARNING_UNKNOWN")]
    MCAWARNINGUNKNOWN = 45,
    /// MCA_ERROR_UNKNOWN
    #[serde(rename = "MCA_ERROR_UNKNOWN")]
    MCAERRORUNKNOWN = 46,
    /// MCA_WARNING_UNKNOWN_NO_CPU
    #[serde(rename = "MCA_WARNING_UNKNOWN_NO_CPU")]
    MCAWARNINGUNKNOWNNOCPU = 47,
    /// MCA_ERROR_UNKNOWN_NO_CPU
    #[serde(rename = "MCA_ERROR_UNKNOWN_NO_CPU")]
    MCAERRORUNKNOWNNOCPU = 48,
    /// MCA_WARNING_CMC_THRESHOLD_EXCEEDED
    #[serde(rename = "MCA_WARNING_CMC_THRESHOLD_EXCEEDED")]
    MCAWARNINGCMCTHRESHOLDEXCEEDED = 49,
    /// MCA_WARNING_CPE_THRESHOLD_EXCEEDED
    #[serde(rename = "MCA_WARNING_CPE_THRESHOLD_EXCEEDED")]
    MCAWARNINGCPETHRESHOLDEXCEEDED = 50,
    /// MCA_WARNING_CPU_THERMAL_THROTTLED
    #[serde(rename = "MCA_WARNING_CPU_THERMAL_THROTTLED")]
    MCAWARNINGCPUTHERMALTHROTTLED = 51,
    /// MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED
    #[serde(rename = "MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED")]
    MCAINFOCPUTHERMALTHROTTLINGREMOVED = 52,
    /// MCA_WARNING_CPU
    #[serde(rename = "MCA_WARNING_CPU")]
    MCAWARNINGCPU = 53,
    /// MCA_ERROR_CPU
    #[serde(rename = "MCA_ERROR_CPU")]
    MCAERRORCPU = 54,
    /// MCA_MEMORYHIERARCHY_ERROR
    #[serde(rename = "MCA_MEMORYHIERARCHY_ERROR")]
    MCAMEMORYHIERARCHYERROR = 55,
    /// MCA_TLB_ERROR
    #[serde(rename = "MCA_TLB_ERROR")]
    MCATLBERROR = 56,
    /// MCA_BUS_ERROR
    #[serde(rename = "MCA_BUS_ERROR")]
    MCABUSERROR = 57,
    /// MCA_BUS_TIMEOUT_ERROR
    #[serde(rename = "MCA_BUS_TIMEOUT_ERROR")]
    MCABUSTIMEOUTERROR = 58,
    /// MCA_INTERNALTIMER_ERROR
    #[serde(rename = "MCA_INTERNALTIMER_ERROR")]
    MCAINTERNALTIMERERROR = 59,
    /// MCA_MICROCODE_ROM_PARITY_ERROR
    #[serde(rename = "MCA_MICROCODE_ROM_PARITY_ERROR")]
    MCAMICROCODEROMPARITYERROR = 60,
    /// MCA_EXTERNAL_ERROR
    #[serde(rename = "MCA_EXTERNAL_ERROR")]
    MCAEXTERNALERROR = 61,
    /// MCA_FRC_ERROR
    #[serde(rename = "MCA_FRC_ERROR")]
    MCAFRCERROR = 62,
}

impl Default for MemoryError_Type {
    fn default() -> Self {
        Self::MCAWARNINGCACHE
    }
}

