// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 12/5/2025 using wmigen
//      Source root.WMI
//////////////////////////////////////////////
use crate::wmi;
use crate::cim;


/// MSiSCSI_TCPIPConfig struct
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MSiSCSI_TCPIPConfig {

/// 
    #[serde(rename = "Active")]
    pub active: Option<bool>,

/// Alternate DNS Server
    #[serde(rename = "AlternateDNSServer")]
    pub alternate_dnsserver: Option<ISCSI_IP_Address>,

/// Static Default Gateway IP address
    #[serde(rename = "DefaultGateway")]
    pub default_gateway: Option<ISCSI_IP_Address>,

/// TRUE if the adapter should use DHCP to discovery its IP address information.
    #[serde(rename = "EnableDHCP")]
    pub enable_dhcp: Option<bool>,

/// 
    #[serde(rename = "InstanceName")]
    pub instance_name: Option<String>,

/// IP address of the adapter
    #[serde(rename = "IpAddress")]
    pub ip_address: Option<ISCSI_IP_Address>,

/// IP Versions supported **Add #defines**
    #[serde(rename = "IPVersions")]
    pub ipversions: Option<u32>,

/// Preferred DNS Server
    #[serde(rename = "PreferredDNSServer")]
    pub preferred_dnsserver: Option<ISCSI_IP_Address>,

/// Static Subnet Mask
    #[serde(rename = "SubnetMask")]
    pub subnet_mask: Option<ISCSI_IP_Address>,

/// TRUE if the adapter should use DHCP to discover DNS addresses.
    #[serde(rename = "UseDHCPForDNS")]
    pub use_dhcpfor_dns: Option<bool>,

/// TRUE if the adapter should use an autogenerated and non routable (link local) address as its IP address.
    #[serde(rename = "UseLinkLocalAddress")]
    pub use_link_local_address: Option<bool>,
}

impl MSiSCSI_TCPIPConfig {
    /// Creates a new instance of the struct
    pub fn new() -> Self {
        Self {
            active: None,
            alternate_dnsserver: None,
            default_gateway: None,
            enable_dhcp: None,
            instance_name: None,
            ip_address: None,
            ipversions: None,
            preferred_dnsserver: None,
            subnet_mask: None,
            use_dhcpfor_dns: None,
            use_link_local_address: None,
        }
    }


    /// Sets the value of Active
    pub fn set_active(&mut self, value: bool) {
        self.active = Some(value);
    }

    /// Gets the value of Active
    pub fn get_active(&self) -> Option<&bool> {
        self.active.as_ref()
    }

    /// Sets the value of AlternateDNSServer
    pub fn set_alternate_dnsserver(&mut self, value: ISCSI_IP_Address) {
        self.alternate_dnsserver = Some(value);
    }

    /// Gets the value of AlternateDNSServer
    pub fn get_alternate_dnsserver(&self) -> Option<&ISCSI_IP_Address> {
        self.alternate_dnsserver.as_ref()
    }

    /// Sets the value of DefaultGateway
    pub fn set_default_gateway(&mut self, value: ISCSI_IP_Address) {
        self.default_gateway = Some(value);
    }

    /// Gets the value of DefaultGateway
    pub fn get_default_gateway(&self) -> Option<&ISCSI_IP_Address> {
        self.default_gateway.as_ref()
    }

    /// Sets the value of EnableDHCP
    pub fn set_enable_dhcp(&mut self, value: bool) {
        self.enable_dhcp = Some(value);
    }

    /// Gets the value of EnableDHCP
    pub fn get_enable_dhcp(&self) -> Option<&bool> {
        self.enable_dhcp.as_ref()
    }

    /// Sets the value of InstanceName
    pub fn set_instance_name(&mut self, value: String) {
        self.instance_name = Some(value);
    }

    /// Gets the value of InstanceName
    pub fn get_instance_name(&self) -> Option<&String> {
        self.instance_name.as_ref()
    }

    /// Sets the value of IpAddress
    pub fn set_ip_address(&mut self, value: ISCSI_IP_Address) {
        self.ip_address = Some(value);
    }

    /// Gets the value of IpAddress
    pub fn get_ip_address(&self) -> Option<&ISCSI_IP_Address> {
        self.ip_address.as_ref()
    }

    /// Sets the value of IPVersions
    pub fn set_ipversions(&mut self, value: u32) {
        self.ipversions = Some(value);
    }

    /// Gets the value of IPVersions
    pub fn get_ipversions(&self) -> Option<&u32> {
        self.ipversions.as_ref()
    }

    /// Sets the value of PreferredDNSServer
    pub fn set_preferred_dnsserver(&mut self, value: ISCSI_IP_Address) {
        self.preferred_dnsserver = Some(value);
    }

    /// Gets the value of PreferredDNSServer
    pub fn get_preferred_dnsserver(&self) -> Option<&ISCSI_IP_Address> {
        self.preferred_dnsserver.as_ref()
    }

    /// Sets the value of SubnetMask
    pub fn set_subnet_mask(&mut self, value: ISCSI_IP_Address) {
        self.subnet_mask = Some(value);
    }

    /// Gets the value of SubnetMask
    pub fn get_subnet_mask(&self) -> Option<&ISCSI_IP_Address> {
        self.subnet_mask.as_ref()
    }

    /// Sets the value of UseDHCPForDNS
    pub fn set_use_dhcpfor_dns(&mut self, value: bool) {
        self.use_dhcpfor_dns = Some(value);
    }

    /// Gets the value of UseDHCPForDNS
    pub fn get_use_dhcpfor_dns(&self) -> Option<&bool> {
        self.use_dhcpfor_dns.as_ref()
    }

    /// Sets the value of UseLinkLocalAddress
    pub fn set_use_link_local_address(&mut self, value: bool) {
        self.use_link_local_address = Some(value);
    }

    /// Gets the value of UseLinkLocalAddress
    pub fn get_use_link_local_address(&self) -> Option<&bool> {
        self.use_link_local_address.as_ref()
    }
}

