// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VirtLib.Windows.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VirtualMachineFeature : object, Xunit.IClassFixture<VirtualMachineFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "VirtualMachine.feature"
#line hidden
        
        public VirtualMachineFeature(VirtualMachineFeature.FixtureData fixtureData, VirtLib_Windows_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "VirtualMachine", "\tValidate VM logic and functionality", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get virtual machine from home machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Get virtual machine from home machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public void GetVirtualMachineFromHomeMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get virtual machine from home machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
        testRunner.Given("hyper-v host running on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
     testRunner.When("I get vm with name \"devbox1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
     testRunner.Then("vm should exist with name \"devbox1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get virtual machine from work machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Get virtual machine from work machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public void GetVirtualMachineFromWorkMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get virtual machine from work machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
        testRunner.Given("hyper-v host running on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
        testRunner.When("I get vm with name \"ubuntu\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
        testRunner.Then("vm should exist with name \"ubuntu\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create gen-1 virtual machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Create gen-1 virtual machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public void CreateGen_1VirtualMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create gen-1 virtual machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
        testRunner.Given("hyper-v host running on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
        testRunner.And("ubuntu image \"ubuntu2404.iso\" is at \"X:\\iso\\ubuntu2404.iso\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table3.AddRow(new string[] {
                            "Username",
                            "ubuntu"});
                table3.AddRow(new string[] {
                            "Password",
                            "ubuntu"});
                table3.AddRow(new string[] {
                            "SshPublicKeyFile",
                            "ubuntu_rsa.pub"});
                table3.AddRow(new string[] {
                            "CpuCount",
                            "2"});
                table3.AddRow(new string[] {
                            "MemoryInMB",
                            "2048"});
                table3.AddRow(new string[] {
                            "HardDiskSizeInGB",
                            "20"});
                table3.AddRow(new string[] {
                            "SwitchName",
                            "Default Switch"});
#line 20
        testRunner.When("I create gen 1 vm with name \"ubuntu2\"", ((string)(null)), table3, "When ");
#line hidden
#line 29
        testRunner.Then("vm should exist with name \"ubuntu2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
        testRunner.And("delete vm with name \"ubuntu2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create gen-2 virtual machine")]
        [Xunit.TraitAttribute("FeatureTitle", "VirtualMachine")]
        [Xunit.TraitAttribute("Description", "Create gen-2 virtual machine")]
        [Xunit.TraitAttribute("Category", "integration_test")]
        [Xunit.TraitAttribute("Category", "vm")]
        public void CreateGen_2VirtualMachine()
        {
            string[] tagsOfScenario = new string[] {
                    "integration_test",
                    "vm"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create gen-2 virtual machine", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 34
        testRunner.Given("hyper-v host running on localhost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
        testRunner.And("ubuntu image \"ubuntu2404.iso\" is at \"X:\\iso\\ubuntu2404.iso\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value"});
                table4.AddRow(new string[] {
                            "Username",
                            "ubuntu"});
                table4.AddRow(new string[] {
                            "Password",
                            "ubuntu"});
                table4.AddRow(new string[] {
                            "SshPublicKeyFile",
                            "ubuntu_rsa.pub"});
                table4.AddRow(new string[] {
                            "CpuCount",
                            "2"});
                table4.AddRow(new string[] {
                            "MemoryInMB",
                            "2048"});
                table4.AddRow(new string[] {
                            "HardDiskSizeInGB",
                            "20"});
                table4.AddRow(new string[] {
                            "SwitchName",
                            "Default Switch"});
#line 36
        testRunner.When("I create gen 2 vm with name \"ubuntu3\"", ((string)(null)), table4, "When ");
#line hidden
#line 45
        testRunner.Then("vm should exist with name \"ubuntu3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
        testRunner.And("delete vm with name \"ubuntu3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                VirtualMachineFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                VirtualMachineFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
