<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AzureStack.Common.Config" />
    <PackageReference Include="Microsoft.AzureStack.Common.Monitoring" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtLib.Windows\VirtLib.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Features\ResourceCapability.feature" />
    <Content Include="Features\SanityCheck.feature" />
    <Content Include="Features\VirtualMachine.feature" />
    <Content Include="Features\VSwitch.feature" />
  </ItemGroup>
</Project>
