// -----------------------------------------------------------------------
// <copyright file="WebApiHostSettings.cs" company="Microsoft Corp.">
//     Copyright (c) Microsoft Corp. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Common.Settings;

public class WebApiHostSettings
{
    public string Host { get; set; } = "0.0.0.0";
    public int Port { get; set; } = 19001;
    public bool UseSsl { get; set; }

    /// <summary>
    /// Gets or sets file path to ssl cert. In development, this cert is generated by a tool (cert-installer) and is not checked in.
    /// When deployed to production, the cert is retrieved from key vault and passed during docker build process.
    /// </summary>
    public string CertFile { get; set; }
    public bool UseAadAuth { get; set; }
}