// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 12/5/2025 using wmigen
//      Source Error_CIMStatusCode
//////////////////////////////////////////////

/// Error_CIMStatusCode enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[repr(i32)]
pub enum Error_CIMStatusCode {
    /// CIM_ERR_FAILED
    #[serde(rename = "CIM_ERR_FAILED")]
    CIMERRFAILED = 1,
    /// CIM_ERR_ACCESS_DENIED
    #[serde(rename = "CIM_ERR_ACCESS_DENIED")]
    CIMERRACCESSDENIED = 2,
    /// CIM_ERR_INVALID_NAMESPACE
    #[serde(rename = "CIM_ERR_INVALID_NAMESPACE")]
    CIMERRINVALIDNAMESPACE = 3,
    /// CIM_ERR_INVALID_PARAMETER
    #[serde(rename = "CIM_ERR_INVALID_PARAMETER")]
    CIMERRINVALIDPARAMETER = 4,
    /// CIM_ERR_INVALID_CLASS
    #[serde(rename = "CIM_ERR_INVALID_CLASS")]
    CIMERRINVALIDCLASS = 5,
    /// CIM_ERR_NOT_FOUND
    #[serde(rename = "CIM_ERR_NOT_FOUND")]
    CIMERRNOTFOUND = 6,
    /// CIM_ERR_NOT_SUPPORTED
    #[serde(rename = "CIM_ERR_NOT_SUPPORTED")]
    CIMERRNOTSUPPORTED = 7,
    /// CIM_ERR_CLASS_HAS_CHILDREN
    #[serde(rename = "CIM_ERR_CLASS_HAS_CHILDREN")]
    CIMERRCLASSHASCHILDREN = 8,
    /// CIM_ERR_CLASS_HAS_INSTANCES
    #[serde(rename = "CIM_ERR_CLASS_HAS_INSTANCES")]
    CIMERRCLASSHASINSTANCES = 9,
    /// CIM_ERR_INVALID_SUPERCLASS
    #[serde(rename = "CIM_ERR_INVALID_SUPERCLASS")]
    CIMERRINVALIDSUPERCLASS = 10,
    /// CIM_ERR_ALREADY_EXISTS
    #[serde(rename = "CIM_ERR_ALREADY_EXISTS")]
    CIMERRALREADYEXISTS = 11,
    /// CIM_ERR_NO_SUCH_PROPERTY
    #[serde(rename = "CIM_ERR_NO_SUCH_PROPERTY")]
    CIMERRNOSUCHPROPERTY = 12,
    /// CIM_ERR_TYPE_MISMATCH
    #[serde(rename = "CIM_ERR_TYPE_MISMATCH")]
    CIMERRTYPEMISMATCH = 13,
    /// CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED
    #[serde(rename = "CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED")]
    CIMERRQUERYLANGUAGENOTSUPPORTED = 14,
    /// CIM_ERR_INVALID_QUERY
    #[serde(rename = "CIM_ERR_INVALID_QUERY")]
    CIMERRINVALIDQUERY = 15,
    /// CIM_ERR_METHOD_NOT_AVAILABLE
    #[serde(rename = "CIM_ERR_METHOD_NOT_AVAILABLE")]
    CIMERRMETHODNOTAVAILABLE = 16,
    /// CIM_ERR_METHOD_NOT_FOUND
    #[serde(rename = "CIM_ERR_METHOD_NOT_FOUND")]
    CIMERRMETHODNOTFOUND = 17,
    /// CIM_ERR_UNEXPECTED_RESPONSE
    #[serde(rename = "CIM_ERR_UNEXPECTED_RESPONSE")]
    CIMERRUNEXPECTEDRESPONSE = 18,
    /// CIM_ERR_INVALID_RESPONSE_DESTINATION
    #[serde(rename = "CIM_ERR_INVALID_RESPONSE_DESTINATION")]
    CIMERRINVALIDRESPONSEDESTINATION = 19,
    /// CIM_ERR_NAMESPACE_NOT_EMPTY
    #[serde(rename = "CIM_ERR_NAMESPACE_NOT_EMPTY")]
    CIMERRNAMESPACENOTEMPTY = 20,
    /// CIM_ERR_INVALID_ENUMERATION_CONTEXT
    #[serde(rename = "CIM_ERR_INVALID_ENUMERATION_CONTEXT")]
    CIMERRINVALIDENUMERATIONCONTEXT = 21,
    /// CIM_ERR_INVALID_OPERATION_TIMEOUT
    #[serde(rename = "CIM_ERR_INVALID_OPERATION_TIMEOUT")]
    CIMERRINVALIDOPERATIONTIMEOUT = 22,
    /// CIM_ERR_PULL_HAS_BEEN_ABANDONED
    #[serde(rename = "CIM_ERR_PULL_HAS_BEEN_ABANDONED")]
    CIMERRPULLHASBEENABANDONED = 23,
    /// CIM_ERR_PULL_CANNOT_BE_ABANDONED
    #[serde(rename = "CIM_ERR_PULL_CANNOT_BE_ABANDONED")]
    CIMERRPULLCANNOTBEABANDONED = 24,
    /// CIM_ERR_FILTERED_ENUMERATION_NOT_SUPPORTED
    #[serde(rename = "CIM_ERR_FILTERED_ENUMERATION_NOT_SUPPORTED")]
    CIMERRFILTEREDENUMERATIONNOTSUPPORTED = 25,
    /// CIM_ERR_CONTINUATION_ON_ERROR_NOT_SUPPORTED
    #[serde(rename = "CIM_ERR_CONTINUATION_ON_ERROR_NOT_SUPPORTED")]
    CIMERRCONTINUATIONONERRORNOTSUPPORTED = 26,
    /// CIM_ERR_SERVER_LIMITS_EXCEEDED
    #[serde(rename = "CIM_ERR_SERVER_LIMITS_EXCEEDED")]
    CIMERRSERVERLIMITSEXCEEDED = 27,
    /// CIM_ERR_SERVER_IS_SHUTTING_DOWN
    #[serde(rename = "CIM_ERR_SERVER_IS_SHUTTING_DOWN")]
    CIMERRSERVERISSHUTTINGDOWN = 28,
    /// CIM_ERR_QUERY_FEATURE_NOT_SUPPORTED
    #[serde(rename = "CIM_ERR_QUERY_FEATURE_NOT_SUPPORTED")]
    CIMERRQUERYFEATURENOTSUPPORTED = 29,
    /// DMTF_Reserved
    #[serde(rename = "DMTF_Reserved")]
    DMTFReserved = 30,
}

impl Default for Error_CIMStatusCode {
    fn default() -> Self {
        Self::CIMERRFAILED
    }
}

