name: build windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: virtlib.sln
      Test_Project_Path: VirtLib.Windows.Tests\VirtLib.Windows.Tests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0
    - name: Configure NuGet to use GitHub Packages
      run: |
        dotnet nuget update source GitHub --username smartpcr --password ${{ secrets.NUGET_AUTH_TOKEN }} --store-password-in-clear-text
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
    - name: Restore
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        Configuration: ${{ matrix.configuration }}
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test --filter Category=unit_test
