name: build windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: virtlib.sln
      Test_Project_Path: VirtLib.Windows.Tests\VirtLib.Windows.Tests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Credential Provider
      run: |
        $credProviderUrl = "https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1"
        Invoke-Expression (Invoke-WebRequest $credProviderUrl).Content
    - name: Setup NuGet Source and Authenticate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      run: |
        dotnet nuget add source --name GitHub --source https://nuget.pkg.github.com/smartpcr/index.json --username smartpcr --password $NUGET_AUTH_TOKEN --store-password-in-clear-text
    - name: Restore
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        Configuration: ${{ matrix.configuration }}
    - name: Build
      run: dotnet build --configuration Debug
    - name: Test
      run: dotnet test
